name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  test_and_build:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  image_publish:
    name: Publish Image
    runs-on: ubuntu-latest
    needs: [test_and_build]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp
      - name: Publish image
        run: |
          docker load --input /tmp/image.tar
          docker push --all-tags ${{ github.repository }}
